### ISSUE TITLE
Hot to get bytea from Postgres?

### ISSUE THREAD

**Issue by bubnenkoff** [IrenejMarc/dpq#4]
I need to get `bytea` binary blob. How can I do it with your driver?

```
	ubyte [] x;
	
	foreach(row; r)
	{
		x = row[0].as!ubyte[]; // or how?
		readln;
	}
```

**Comment by IrenejMarc** [comment]
You should use `x = row[0].as!(ubyte[]);`

**Comment by bubnenkoff** [comment]
I tried it, but without success
http://forum.dlang.org/post/xwvqbtazbqupbvvkpsvt@forum.dlang.org
Does it work for you?

**Comment by IrenejMarc** [comment]
The reason why .as returns Nullable is because any value obtained from PostgreSQL can be null.
`row[0].as!(ubyte[])`, will return `Nullable!(ubyte[])`, which you can then check with the `isNull` method.
[More info here](https://dlang.org/phobos/std_typecons.html#.Nullable)

That being said, there does indeed seem to be a problem with BYTEA handling (wrong result), which I will look into today.

**Comment by IrenejMarc** [comment]
I've created a minimal working example, arrays inserted with the library work, but I'll look into how, for instance arrays constructed with `{1,2,3}::BYTEA` in PostgreSQL are different.
https://gist.github.com/IrenejMarc/d96473cae3323b4e169d4ad7a587d17f

**Comment by IrenejMarc** [comment]
@bubnenkoff is this resolved? Should I close this?

**Comment by bubnenkoff** [comment]
Yeah

пятница, 29 апреля 2016 г. пользователь Irenej Marc написал:
